/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package silaris_client.menu;

import java.awt.Font;
import silaris_client.Main;
import silaris_client.ReaderConfig.ReaderManager;
import silaris_client.panel.PanelLogLinen;
import silaris_client.panel.PanelReaderTest;
import silaris_client.panel.Panel_LinenKeluar;
import silaris_client.panel.Panel_LinenMasuk;

/**
 *
 * @author HP
 */
public class MenuLaundry extends javax.swing.JPanel {

//    private Main main;
    public MenuLaundry(Panel_LinenMasuk panelMasuk,
                       Panel_LinenKeluar panelKeluar,
                       PanelLogLinen panelLog) {
//        this.main=main;
        initComponents();
        
//        ReaderManager manager = new ReaderManager();
        // set font tab menjadi Times New Roman
        tabbedMenuLaundry.setFont(new Font("Times New Roman", Font.PLAIN, 14));
        tabbedMenuLaundry.addTab("Linen Masuk ", panelMasuk);
        tabbedMenuLaundry.addTab("Linen Keluar ", panelKeluar);
        tabbedMenuLaundry.addTab("History Linen ", panelLog);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedMenuLaundry = new silaris_client.tabbed.TabbedPaneCustom();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedMenuLaundry, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedMenuLaundry, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private silaris_client.tabbed.TabbedPaneCustom tabbedMenuLaundry;
    // End of variables declaration//GEN-END:variables
}
