/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package silaris_client.menu;

import java.awt.Font;
import silaris_client.panel.PanelDataLinen;
import silaris_client.panel.PanelRuangan;

/**
 *
 * @author HP
 */
public class MenuMasterData extends javax.swing.JPanel {

    /**
     * Creates new form MenuMasterData
     */
    public MenuMasterData() {
        initComponents();
        // set font tab menjadi Times New Roman
        tabbedMenuMasterData.setFont(new Font("Times New Roman", Font.PLAIN, 14));
        tabbedMenuMasterData.addTab("Data Linen", new PanelDataLinen());
        tabbedMenuMasterData.addTab("Data Ruangan", new PanelRuangan());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedMenuMasterData = new silaris_client.tabbed.TabbedPaneCustom();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedMenuMasterData, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedMenuMasterData, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private silaris_client.tabbed.TabbedPaneCustom tabbedMenuMasterData;
    // End of variables declaration//GEN-END:variables
}
