/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package silaris_client.panel;

import java.util.UUID;
import javax.swing.JOptionPane;
import silaris_client.dao.RuanganDAO;
import silaris_client.model.Ruangan;

/**
 *
 * @author ASUS
 */

public class PanelRuanganDialog extends javax.swing.JDialog {
    private PanelRuangan panel;
    private String id = null;  // ID disimpan tapi tidak ditampilkan
    private Ruangan ruangan;

    public PanelRuanganDialog(java.awt.Frame parent,
                              PanelRuangan panel,
                              Ruangan r) {
        super(parent, true);
        initComponents();

        this.panel = panel;
        this.ruangan = r;
        
        if (r == null) {
            // Mode Tambah
            setTitle("Tambah Ruangan");
            btnSimpan.setText("Simpan");
        } else {
            // Mode Edit
            setTitle("Edit Ruangan");
            btnSimpan.setText("Update");

            // **Set ID** untuk update tapi tidak ditampilkan
           this.id = r.id; 
            lblId_r.setText("ID Ruangan : " + r.id);
            txtKode.setText(r.kodeRuangan);
            txtNama.setText(r.namaRuangan);
            txtKeterangan.setText(r.keterangan);
        }

        setLocationRelativeTo(parent);
    }

    
    private String generateId() {
        return UUID.randomUUID().toString(); // 054f6ba8-b252-43f8-a4f3-61dc1f4b2972
    }
    
    private void simpan() {
        String kode = txtKode.getText().trim();
        String nama = txtNama.getText().trim();
        String ket  = txtKeterangan.getText().trim();

        if (kode.isEmpty() || nama.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Kode dan Nama wajib diisi!");
            return;
        }

        try {
            // Buat object model
            Ruangan r = new Ruangan();
            
             // Hanya generate ID jika mode Tambah
            if (this.id == null) {
                this.id = generateId(); // atau generateIdRandom()
            }
            
            r.id = this.id;
            lblId_r.setText(r.id); 
            r.kodeRuangan = kode;
            r.namaRuangan = nama;
            r.keterangan = ket;

            // Panggil DAO
            RuanganDAO dao = new RuanganDAO();

            if (ruangan == null) {
                // Mode tambah
                dao.insert(r);
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
            } else {
                // Mode edit → update data yang dipilih
                dao.update(r);
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
            }

            panel.loadData(); // refresh tabel
            Panel_LinenKeluar.refreshCombo();
            dispose();
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Gagal simpan: " + e.getMessage());
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKeterangan = new javax.swing.JTextField();
        lblId_r = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnSimpan, new java.awt.GridBagConstraints());

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel3.add(btnBatal, new java.awt.GridBagConstraints());

        jPanel2.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("Kode Ruangan:");
        jPanel2.add(jLabel1);
        jPanel2.add(txtKode);

        jLabel2.setText("Nama Ruangan:");
        jPanel2.add(jLabel2);
        jPanel2.add(txtNama);

        jLabel3.setText("Keterangan:");
        jPanel2.add(jLabel3);
        jPanel2.add(txtKeterangan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblId_r, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblId_r, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
       simpan();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
       dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelRuanganDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelRuanganDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelRuanganDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelRuanganDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                PanelRuanganDialog dialog = new PanelRuanganDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblId_r;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
