
package silaris_client.panel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import silaris_client.config.SQLiteConfig;
import silaris_client.model.Ruangan;
public class PanelLinenKeluar extends JPanel {

    private DefaultTableModel model;
//    private JComboBox<Ruangan> cbRuangan;
    public PanelLinenKeluar() {
       initComponents();
       setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
      
         // === ComboBox Ruangan ===
        cbRuangan = new JComboBox<>();
        add(new JLabel("Pilih Ruangan:"));
        add(cbRuangan);

        model = new DefaultTableModel(new Object[]{"EPC"}, 0);
        JTable table = new JTable(model);

        JButton btnStart = new JButton("Start Scan");
        JButton btnStop = new JButton("Stop Scan");

        add(new JScrollPane(table));
        add(btnStart);
        add(btnStop);

//        btnStart.addActionListener(e -> startScan());
//        btnStop.addActionListener(e -> stopScan());

        loadRuangan(); 

    }
    
//    private void startScan() {
//        model.setRowCount(0);
//
//        String port = PortConfigService.getPortByType("KELUAR");
//
//        reader = new RMT01ReaderService(port, this);
//        reader.start();
//    }
//    
//    private void stopScan() {
//        if (reader != null) {
//            reader.stop();
//        }
//    }
//
//    @Override
//    public void onTagRead(String epc) {
//
//        SwingUtilities.invokeLater(() -> {
//            model.addRow(new Object[]{epc});
//        });
//    }
       

    private void loadRuangan() {
    try {
        cbRuangan.removeAllItems();

        String sql = "SELECT * FROM ruangan ORDER BY kode_ruangan ASC";
        Connection c = SQLiteConfig.connect();
        Statement s = c.createStatement();
        ResultSet r = s.executeQuery(sql);

       while (r.next()) {

           Ruangan ruangan = new Ruangan();
            ruangan.id = r.getString("id");
            ruangan.kodeRuangan = r.getString("kode_ruangan");
            ruangan.namaRuangan = r.getString("nama_ruangan");
            ruangan.keterangan = r.getString("keterangan");

            cbRuangan.addItem(ruangan);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load ruangan: " + e.getMessage());
   }
  }



    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cbRuangan = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setText("Start Scan");
        jPanel3.add(jButton1, new java.awt.GridBagConstraints());

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton2.setText("Stop Scan");
        jPanel3.add(jButton2, new java.awt.GridBagConstraints());

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton3.setText("Proses");
        jPanel3.add(jButton3, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel4.add(cbRuangan, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Ruangan> cbRuangan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
