/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package silaris_client.panel;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import silaris_client.Main;
import silaris_client.dao.RuanganDAO;
import silaris_client.model.Ruangan;

/**
 *
 * @author ASUS
 */
public class PanelRuangan extends javax.swing.JPanel {
    private Main main;
    DefaultTableModel r;
    private PanelRuangan panel;
    private Ruangan ruangan;
    RuanganDAO dao = new RuanganDAO();
    private Object id;
    public PanelRuangan(Main main) {
        this.main = main;
        initComponents();
         r = new DefaultTableModel(
            new Object[]{"No","ID Ruangan","Kode Ruangan","Nama Ruangan", "Keterangan"},0
        );
        tblRuangan.setModel(r);
        
        tblRuangan.getColumnModel().getColumn(1).setMinWidth(0);
        tblRuangan.getColumnModel().getColumn(1).setMaxWidth(0);
        tblRuangan.getColumnModel().getColumn(1).setWidth(0);
        
         
        loadData(); 
        setupTableColumnWidth();
    }
    
    private void setupTableColumnWidth() {
        TableColumnModel columnModel = tblRuangan.getColumnModel();
        TableColumn colNo = columnModel.getColumn(0);
        colNo.setMinWidth(30);
        colNo.setPreferredWidth(40);
        colNo.setMaxWidth(50);
    }
    
    public void loadData() {
        r.setRowCount(0);
        int no = 1;
        try {
            RuanganDAO dao = new RuanganDAO();

            for (Ruangan ruangan : dao.getAll()) {
                r.addRow(new Object[]{
                    no++,
                    ruangan.id,
                    ruangan.kodeRuangan,
                    ruangan.namaRuangan,
                    ruangan.keterangan
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Load gagal: " + e.getMessage());
        }
    }
    
    private void edit() {
        int row = tblRuangan.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Pilih data dulu!");
            return;
        }

        Ruangan r = new Ruangan();
        r.id = tblRuangan.getValueAt(row, 0).toString();
        r.kodeRuangan = tblRuangan.getValueAt(row, 1).toString();
        r.namaRuangan = tblRuangan.getValueAt(row, 2).toString();
        r.keterangan  = tblRuangan.getValueAt(row, 3).toString();

        new PanelRuanganDialog(
            (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
            this,
            r
        ).setVisible(true);
        Panel_LinenKeluar.refreshCombo();
    }
    
    private void delete() {
        try {
            int r = tblRuangan.getSelectedRow(); // ambil baris yang dipilih
            if (r < 0) {
                JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!");
                return;
            }

            // Ambil ID dari kolom pertama (asumsikan kolom 0 = ID)
             String id = tblRuangan.getValueAt(r, 0).toString();

            // Konfirmasi sebelum hapus
            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Apakah Anda yakin ingin menghapus ruangan ini?",
                    "Konfirmasi Hapus",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {
                RuanganDAO dao = new RuanganDAO();
                dao.delete(id); // panggil DAO delete berdasarkan ID
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");

                loadData(); // refresh tabel
                Panel_LinenKeluar.refreshCombo();
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal hapus: " + e.getMessage());
        }
   }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRuangan = new javax.swing.JTable();

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        btnTambah.setBackground(new java.awt.Color(51, 255, 51));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel4.add(btnTambah, new java.awt.GridBagConstraints());

        btnEdit.setBackground(new java.awt.Color(255, 255, 51));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel4.add(btnEdit, new java.awt.GridBagConstraints());

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btnDelete, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);

        jPanel5.setLayout(new java.awt.BorderLayout());

        tblRuangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRuangan);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        java.awt.Frame parent = (java.awt.Frame) 
                javax.swing.SwingUtilities.getWindowAncestor(this);

        PanelRuanganDialog dialog =
                new PanelRuanganDialog(parent, this, null);

        dialog.setLocationRelativeTo(parent);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        edit();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        delete();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRuangan;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
}
